phageParser/phageParser

Makefile

Trivial typo in comment

---

cas_in_gb.pl
cas_in_gb_v2.pl
cpanfile
data/Genbank_example.txt

It adds some best practices to the existing file but creates an entirely new script in Perl to parse genbank file, detect Cas(3,6,9) products and spit it out along with type. Hope it's OK, but please if it's not just tell me, I won't be able to do much stuff over the weekend but will be back to normal next Tuesday

Doing some stuff processing some stuff

---

cas_per_species.pl

output is a table with organisms in rows and unique protein products in columns, with counts for each protein product in the table itself. also contains info on whether the organism belongs to bacteria or archea.

I wrote a script that takes the output from Daisie's script and produces a table

---

cas_in_gb_v2.pl

I rewrote a few bits so we don’t use outside dependencies anymore.

Removes unneeded dependencies

---

cas_in_gb_v2.pl

Putting back the protein name

---

extract_CRISPRdb.py

I've written a script to bulk download CRISPR database files, to extract begin and end positions and to write a result .csv file. I hope this will help.

Extract CRISPR location in bacterial genome from CRISPR database

---

PFAM_db.py

#70:
I have created functions to:
- Extract the translated coding regions of the genome from the genbank file (details below).
- Submit the translations to Pfam.
At the moment, we have to write the path of the file to parse and the output file is in the CSV format.

Add PFAM DB parser

---

README.md

Since this is the first time I pull something (without instructions) let me know if it went through alright.
Also, if you want I could add or change/expand more on the info.
Let me know! :)

Updated "About the CRISPR system"  in README.md

---

CODE-OF-CONDUCT.md

Just links to Mozilla Community Participation Guidelines so far.

First draft of code of conduct

---

addRepeatAndSpacersToDB.py
jointable.py

Populating sql database from Spacers and Repeats files to resolve issue #99

Adding new file to populate database from Spacers and Repeats

---

.gitignore

Alteration of gitignore for OSX

---

phageAPI/populate_organism.py

- Fetches a list of accession ids from data/bac_accession_list.txt and matches each id with the description that is pulled from Genbank nucleotide database which is then modeled as a dictionary.
- The dictionary pair is then saved as Django Organism models meanwhile also checking to make sure no duplicate entries are made.
- The script can also be used as a starting point for populating other related models as it demonstrates Django model creation conventions.
#124 
To use, run the script with an extra argument of e-mail address. For testing purposes, a clean database with no tables is preferred. For clearing the database, old db.sqlite3 can be moved or deleted and then python manage.py migrate can be run to initialize a new database.

Created a script to populate Organism model in Django app

---

phageAPI/restapi/models.py

Fixes a merge issue with models.py by removing the old code. #126

Removes unused code from models.py

---

phageAPI/addspacerandrepeat.py

added script to populate spacer + repeat tables

---

phageAPI/phageAPI/urls.py
phageAPI/populate_organism.py
phageAPI/populate_osrpair.py
phageAPI/prunedict.py
phageAPI/restapi/models.py
phageAPI/restapi/serializers.py
phageAPI/restapi/views.py

This PR removes the SpacerRepeatPair model and adds or updates api entry points for Spacer, Repeat, OrganismSpacerRepeatPair and Organism models. It also resolves #131 by including a script for populating OrganismSpacerRepeatPair model.

Modify db schema and add scripts for populating db

---

phageAPI/restapi/serializers.py

The addition of the new field is done on the serializer level by using SerializerMethodField which can calculate the length when requested.

Adds dynamically calculated length field to Repeat and Spacer objects.

---

PFAM_db.py
README.md

Merge needed for future commits into django-dev.

Merge master into django-dev

---

phageAPI/addcrisprtypes.py

The initial PR downloads all the genbank files for each Organism in API and then runs hmmscan with a given database of profiles to find similarity between CRISPR proteins and the proteins in that organism. This script can be extended to also address issues in #148 .

Script for downloading Organism genbank files and identifying CRISPR proteins

---

README.md

PR adds a guide on how to install the phageParser with using virtual environments for future collaboration work.

Installation in Readme

---

phageAPI/restapi/models.py
phageAPI/restapi/serializers.py
phageAPI/restapi/views.py

Add OrganismCas model

---

setup.py

It's outdated and I deleted it before...

Remove ez_setup.py from install.

---

phageAPI/populate_anticrispr.py

This script populates the restapi_anticrispr table based on the table of
sequences in https://www.nature.com/articles/nmicrobiol201685
This also uses argparse to give nice help output.

Add populate_anticrispr.py

---

.coveragerc
.travis.yml
requirements.txt
setup.py

For fun, let's see if this works...
Also, fix a cleanup a couple of testing things that are no longer needed.

Enable Codecov

---

blast.py

Adds `blast.py`, a general purpose blast script that converts input to a BLAST+ command line call. Allows for blasting a file against either an NCBI database or an existing file. This addresses issue #189.

Added blast.py script

---

phageAPI/restapi/models.py

Modifies the field constraints and changes evalue to float.

---

addcrisprtypes.py
populate_casgenes.py

populate_casgenes now skips proteins with incomplete position data

---

restapi/serializers.py

Fields yield the related cas proteins and possible crispr types

Adds two method fields to organism

---

phageAPI/urls.py
populate.py
restapi/models.py
restapi/serializers.py
restapi/views.py

Modify model schema

---

phageAPI/urls.py
restapi/models.py
restapi/serializers.py
restapi/views.py

This model helps store the spacer hits in an organism that target the organism's DNA.

Adds the model organismselfspacer

---

parserscripts/filterByExpect.py

Modifies filterbyexpect

---

blastselftargets.py
populate_selftargets.py

Adds initial script for blasting self targeting spacers

---

parserscripts/collect_accessions.py

This is a rewrite to use Pandas for cleaner ID extraction and also addresses #244

Re-write to use pandas and add argument parsing

---

.editorconfig
devscripts/README.md
devscripts/bootstrap.sh
devscripts/server.sh
devscripts/setup.sh
requirements.txt

I've used these scripts to document and automate my development environment setup on Ubuntu (well, the Linux Subsystem on Windows 10) with pip.

Development environment setup scripts

---

README.md

http://crispr.u-psud.fr/crispr/) moved in to http://crispr.i2bc.paris-saclay.fr/
Good first bugs link updated to https://github.com/goyalsid/phageParser/labels/good%20first%20issue

updated broken links.

---

demos/Repeat array class demo.ipynb

Correct file loading issue in repeats demo notebook

---

demos/Bacteria-phage interactions.ipynb

The remaining steps we did a while ago, but I still need to clean them up and put them in here.

Beginnings of the pipeline to match spacers and phages

---

demos/Bacteria-phage interactions.ipynb

Bac phage interactions

---

README.md

Add section on running Jupyter notebooks
